version: '3.8'
services:
  apcom:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_PORT: ${APP_DOCKER_PORT_PROD:-3000}
    container_name: apcom
    env_file:
      - .env
    ports:
      - '${APP_DOCKER_PORT_PROD:-3000}:${APP_DOCKER_PORT_PROD:-3000}'
    restart: always
  apcom-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_PORT: ${APP_DOCKER_PORT_DEV:-3200}
    container_name: apcom-dev
    env_file:
      - .env
    ports:
      - '${APP_DOCKER_PORT_DEV:-3200}:${APP_DOCKER_PORT_DEV:-3200}'
