version: '3.8'
services:
  apcom:
    image: ${APP_DOCKER_REGISTRY_DOMAIN}/apcom
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: production
        DOCKER_PORT: ${APP_DOCKER_PORT:-3000}
    container_name: apcom
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
    env_file:
      - .env
    environment:
      APP_ENV: production
    ports:
      - '${APP_DOCKER_PORT:-3000}:${APP_DOCKER_PORT:-3000}'
    restart: always
  apcom-staging:
    image: ${APP_DOCKER_REGISTRY_DOMAIN}/apcom-staging
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: staging
        DOCKER_PORT: ${APP_STAGING_DOCKER_PORT:-3200}
    container_name: apcom-staging
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
    env_file:
      - .env
    environment:
      APP_ENV: staging
    ports:
      - '${APP_STAGING_DOCKER_PORT:-3200}:${APP_STAGING_DOCKER_PORT:-3200}'
